"""Writes Sources/BlenderLocalBridge/TexturePaintCurves.swift from Blender.

One of the brushes texture paint starts from uses a custom falloff curve rather
than an analytic preset: "Paint Hard" (Draw). Blender evaluates
such a curve through a 257-entry table (CurveMapping, CM_TABLE + 1) and
interpolates linearly between entries, so sampling `evaluate` at the same 257
positions reproduces its falloff exactly.

    Blender -b --factory-startup --python tests/texpaint/blender/bake_curves.py -- <out.swift>

tests/texpaint/blender/verify.py checks the committed table against Blender
every time it runs, so a stale bake fails rather than drifts.
"""
import bpy, glob, os, sys

OUT = sys.argv[-1]
ROOT = glob.glob(os.path.join(os.path.dirname(bpy.app.binary_path), "..", "Resources", "*",
                              "datafiles", "assets", "brushes"))[0]


def table(filename, brush_name):
    with bpy.data.libraries.load(os.path.join(ROOT, filename), assets_only=True) as (src, dst):
        dst.brushes = [brush_name]
    brush = dst.brushes[0]
    assert brush.curve_distance_falloff_preset == 'CUSTOM', brush.curve_distance_falloff_preset
    curve = brush.curve_distance_falloff
    curve.initialize()
    return [curve.evaluate(curve.curves[0], i / 256.0) for i in range(257)]


def swift(name, values, doc):
    rows = []
    for i in range(0, len(values), 8):
        rows.append("        " + ", ".join("%.6f" % v for v in values[i:i + 8]) + ",")
    return "\n".join(["    /// " + line for line in doc] +
                     ["    public static let %s: [Float] = [" % name] + rows + ["    ]"])


body = [
    "// Generated by tests/texpaint/blender/bake_curves.py from Blender %s's" % bpy.app.version_string.split()[0],
    "// essentials brush assets. Regenerate rather than edit; verify.py compares it",
    "// with Blender on every run.",
    "",
    "/// Blender's custom brush falloff curves, as the 257-entry tables Blender",
    "/// itself evaluates them through (`CurveMapping`, `CM_TABLE + 1`). Index `i`",
    "/// is the falloff at distance `i / 256` of the radius.",
    "public enum TexturePaintCurves {",
    swift("paintHard", table("essentials_brushes-mesh_texture.blend", "Paint Hard"),
          ["\"Paint Hard\", essentials_brushes-mesh_texture.blend: full strength to",
           "three quarters of the radius, then a short soft edge."]),
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(body))
print("wrote", OUT)
